type LocationType = 'FileSystem' | 'Remote' | 'Virtual' | 'Offline';
type SortOrder = 'Ascending' | 'Descending';
export type ItemType =
  | 'AggregateFolder'
  | 'Audio'
  | 'AudioBook'
  | 'BasePluginFolder'
  | 'Book'
  | 'BoxSet'
  | 'Channel'
  | 'ChannelFolderItem'
  | 'CollectionFolder'
  | 'Episode'
  | 'Folder'
  | 'Genre'
  | 'ManualPlaylistsFolder'
  | 'Movie'
  | 'LiveTvChannel'
  | 'LiveTvProgram'
  | 'MusicAlbum'
  | 'MusicArtist'
  | 'MusicGenre'
  | 'MusicVideo'
  | 'Person'
  | 'Photo'
  | 'PhotoAlbum'
  | 'Playlist'
  | 'PlaylistsFolder'
  | 'Program'
  | 'Recording'
  | 'Season'
  | 'Series'
  | 'Studio'
  | 'Trailer'
  | 'TvChannel'
  | 'TvProgram'
  | 'UserRootFolder'
  | 'UserView'
  | 'Video'
  | 'Year';
type ItemFilter =
  | 'IsFolder'
  | 'IsNotFolder'
  | 'IsUnplayed'
  | 'IsPlayed'
  | 'IsFavorite'
  | 'IsResumable'
  | 'Likes'
  | 'Dislikes'
  | 'IsFavoriteOrLikes';
type MediaType = 'Unknown' | 'Video' | 'Audio' | 'Photo' | 'Book';
type ImageType =
  | 'Primary'
  | 'Art'
  | 'Backdrop'
  | 'Banner'
  | 'Logo'
  | 'Thumb'
  | 'Disc'
  | 'Box'
  | 'Screenshot'
  | 'Menu'
  | 'Chapter'
  | 'BoxRear'
  | 'Profile';
type VideoType = 'VideoFile' | 'Iso' | 'Dvd' | 'BluRay';
type SeriesStatus = 'Continuing' | 'Ended' | 'Unreleased';

interface ItemsQueryParams {
  /** Required when not using an API key. */
  userId?: string;
  maxOfficialRating?: string;
  hasThemeSong?: boolean;
  hasThemeVideo?: boolean;
  hasSubtitles?: boolean;
  hasSpecialFeature?: boolean;
  hasTrailer?: boolean;
  adjacentTo?: string;
  indexNumber?: number;
  parentIndexNumber?: number;
  hasParentalRating?: boolean;
  isHd?: boolean;
  is4K?: boolean;
  locationTypes?: LocationType[];
  excludeLocationTypes?: LocationType[];
  isMissing?: boolean;
  isUnaired?: boolean;
  minCommunityRating?: number;
  minCriticRating?: number;
  minPremiereDate?: string;
  minDateLastSaved?: string;
  minDateLastSavedForUser?: string;
  maxPremiereDate?: string;
  hasOverview?: boolean;
  hasImdbId?: boolean;
  hasTmdbId?: boolean;
  hasTvdbId?: boolean;
  isMovie?: boolean;
  isSeries?: boolean;
  isNews?: boolean;
  isKids?: boolean;
  isSports?: boolean;
  excludeItemIds?: string[];
  startIndex?: number;
  limit?: number;
  recursive?: boolean;
  searchTerm?: string;
  sortOrder?: SortOrder[];
  parentId?: string;
  fields?: string[];
  excludeItemTypes?: ItemType[];
  includeItemTypes?: ItemType[];
  filters?: ItemFilter[];
  isFavorite?: boolean;
  mediaTypes?: MediaType[];
  imageTypes?: ImageType[];
  sortBy?: string[];
  isPlayed?: boolean;
  genres?: string[];
  officialRatings?: string[];
  tags?: string[];
  years?: number[];
  enableUserData?: boolean;
  imageTypeLimit?: number;
  enableImageTypes?: ImageType[];
  person?: string;
  personIds?: string[];
  personTypes?: string[];
  studios?: string[];
  artists?: string[];
  excludeArtistIds?: string[];
  artistIds?: string[];
  albumArtistIds?: string[];
  contributingArtistIds?: string[];
  albums?: string[];
  albumIds?: string[];
  ids?: string[];
  videoTypes?: VideoType[];
  minOfficialRating?: string;
  isLocked?: boolean;
  isPlaceHolder?: boolean;
  hasOfficialRating?: boolean;
  collapseBoxSetItems?: boolean;
  minWidth?: number;
  minHeight?: number;
  maxWidth?: number;
  maxHeight?: number;
  is3D?: boolean;
  seriesStatus?: SeriesStatus[];
  nameStartsWithOrGreater?: string;
  nameStartsWith?: string;
  nameLessThan?: string;
  studioIds?: string[];
  genreIds?: string[];
  enableTotalRecordCount?: boolean;
  enableImages?: boolean;
}